export const ADD_ROW = 'ADD_ROW';

export const RESET_TABLE = 'RESET_TABLE';
export const ADD_COLUMN_HEADER = 'ADD_COLUMN_HEADER';
export const UPDATE_COLUMN_HEADER = 'UPDATE_COLUMN_HEADER';
export const UPDATE_ROW_NAME = 'UPDATE_ROW_NAME';
export const UPDATE_ROW_DATA = 'UPDATE_ROW_DATA';

export const CHANGE_COLUMN = 'CHANGE_COLUMN';
export const CHANGE_ROW = 'CHANGE_ROW';

export const CHOOSE_TYPE = 'CHOOSE_TYPE';

export const IMPORT_FILE = 'IMPORT_FILE';
export const EXPORT_FILE = 'EXPORT_FILE';

export const CHOOSE_ALL_COLUMNS = 'CHOOSE_ALL_COLUMNS';
export const CANCEL_ALL_COLUMNS = 'CANCEL_ALL_COLUMNS';
export const CHOOSE_ALL_ROWS = 'CHOOSE_ALL_ROWS';
export const CANCEL_ALL_ROWS = 'CANCEL_ALL_ROWS';